### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by rozanecm** [rozanecm/6606_TP-filtros#1]
- [ ] agregar link a informe en readme
- [ ] completar informe con la practica de laboratorio
- [ ] incluir en el informe imagenes de los filtros hechos
